[project]
name = 'erc-8004-stacks-contracts'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'

[[project.requirements]]
contract_id = 'SP2PABAF9FTAJYNFZH93XENAJ8FVY99RRM50D2JG9.nft-trait'

[contracts.identity-registry-v2]
path = 'contracts/identity-registry-v2.clar'
clarity_version = 4
epoch = 'latest'

[contracts.reputation-registry-v2]
path = 'contracts/reputation-registry-v2.clar'
clarity_version = 4
epoch = 'latest'

[contracts.validation-registry-v2]
path = 'contracts/validation-registry-v2.clar'
clarity_version = 4
epoch = 'latest'

[contracts.identity-registry-v3]
path = 'contracts/identity-registry-v3.clar'
clarity_version = 4
epoch = 'latest'

[contracts.identity-registry-trait-v3]
path = 'contracts/traits/identity-registry-trait-v3.clar'
clarity_version = 4
epoch = 'latest'

[contracts.identity-registry-trait-v2]
path = 'contracts/traits/identity-registry-trait-v2.clar'
clarity_version = 4
epoch = 'latest'

[contracts.reputation-registry-trait-v2]
path = 'contracts/traits/reputation-registry-trait-v2.clar'
clarity_version = 4
epoch = 'latest'

[contracts.validation-registry-trait-v2]
path = 'contracts/traits/validation-registry-trait-v2.clar'
clarity_version = 4
epoch = 'latest'

[repl.analysis]
passes = ['call_checker', 'check_checker']

[repl.analysis.lints]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
