[project]
name = 'owner-agent-registry'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.addon-attestation]
path = 'contracts/addon-attestation.clar'
clarity_version = 4
epoch = 'latest'

[contracts.agent-account-example]
path = 'contracts/agent-account-example.clar'
clarity_version = 4
epoch = 'latest'

[contracts.base-registry]
path = 'contracts/base-registry.clar'
clarity_version = 4
epoch = 'latest'
[repl.analysis]
passes = [
    'call_checker',
    'check_checker',
]

[repl.analysis.lints]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
